name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: sudo docker build -t web:juice-shop .

    - name: Run the Docker image
      run: sudo docker run -d -p 3000:3000 --name juice-shop-container web:juice-shop
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run vulnerability scanner
      run: |
        python vulnerability_scanner.py
