name: Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest

    env:
      URLS_FILE: 'urls.txt'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: List files
      run: ls -la

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run vulnerability scanner
      run: |
        python ./vulnerability_scanner.py

